#!/usr/bin/env python3
"""OpenClaw spend report (local).

Reads OpenClaw session JSONL logs and prints a short markdown report.
Defaults: last 24 hours.
"""

from __future__ import annotations

import argparse
import datetime as dt
import glob
import json
import os
from collections import Counter, defaultdict
from typing import List, Tuple


def parse_ts(ts: str | None) -> dt.datetime | None:
    if not ts:
        return None
    if ts.endswith("Z"):
        ts = ts[:-1] + "+00:00"
    try:
        return dt.datetime.fromisoformat(ts)
    except Exception:
        return None


def money(x) -> str:
    return f"${x:,.4f}"


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sessions-glob", default=os.path.expanduser("~/.openclaw/agents/main/sessions/*.jsonl"))
    ap.add_argument("--hours", type=float, default=24.0)
    ap.add_argument("--now", default=None, help="ISO timestamp override (for testing)")
    ap.add_argument("--json-out", default=None, help="Write a JSON summary snapshot to this path")
    ap.add_argument("--history-out", default=None, help="Append a JSON snapshot line to this JSONL path")
    ap.add_argument("--coo-log", default=None, help="Path to COO_LOG.md for journal summaries")
    ap.add_argument("--todo", default=None, help="Path to TODO.md for journal context")
    ap.add_argument("--journal-out", default=None, help="Write a JSON journal entry to this path")
    ap.add_argument("--journal-history", default=None, help="Append journal entry JSONL to this path")
    return ap.parse_args()


def read_last_log_block(coo_path: str) -> Tuple[str, List[str]]:
    if not coo_path or not os.path.exists(coo_path):
        return "", []
    with open(coo_path, "r", encoding="utf-8") as f:
        lines = [line.rstrip() for line in f]

    sections: List[Tuple[str, List[str]]] = []
    current_title = None
    current_lines: List[str] = []
    for line in lines:
        if line.startswith("## "):
            if current_title is not None:
                sections.append((current_title, current_lines))
            current_title = line[3:].strip()
            current_lines = []
        elif current_title is not None and line.strip():
            current_lines.append(line.strip())
    if current_title is not None:
        sections.append((current_title, current_lines))
    return sections[-1] if sections else ("", [])


def filter_lines(lines: List[str], keywords: List[str]) -> List[str]:
    results: List[str] = []
    lower_keywords = [k.lower() for k in keywords]
    for line in lines:
        text = line.lstrip("-* ").strip()
        low = text.lower()
        if any(keyword in low for keyword in lower_keywords):
            results.append(text)
    return results


def parse_todo_items(todo_path: str, max_items: int = 5) -> List[str]:
    if not todo_path or not os.path.exists(todo_path):
        return []
    tasks: List[str] = []
    with open(todo_path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("- [ ]") or stripped.startswith("- []"):
                parts = stripped.split("]", 1)
                if len(parts) > 1:
                    text = parts[1].strip()
                    tasks.append(text)
                    if len(tasks) >= max_items:
                        break
    return tasks


def build_journal_entry(
    now: dt.datetime,
    hours: float,
    total_tokens: int,
    total_cost: float,
    log_title: str,
    log_lines: List[str],
    todo_items: List[str],
) -> dict:
    what_we_did = [line.lstrip("-* ") for line in log_lines[:6]]
    problems = filter_lines(log_lines, ["problem", "issue", "block", "fail"])
    struggles = filter_lines(log_lines, ["struggle", "hard", "challenge", "friction"])
    accomplishments = filter_lines(log_lines, ["win", "accomplish", "done", "key"]) or what_we_did[:3]

    if not what_we_did:
        what_we_did = ["Captured spend + log data; no explicit notes found."]
    if not problems:
        problems = ["No explicit problems called out in COO log; everything nominal."]
    if not struggles:
        struggles = ["No additional struggles captured."]

    entry = {
        "generatedAt": now.isoformat(timespec="seconds"),
        "windowHours": hours,
        "logDate": log_title,
        "whatWeDid": what_we_did,
        "problemsAndSolutions": problems,
        "struggles": struggles,
        "keyAccomplishments": accomplishments,
        "nextUp": todo_items,
        "notes": [
            f"Spend: ${total_cost:.2f} ({total_tokens:,} tokens)",
            "Journal auto-generated by Maya.",
        ],
    }
    return entry


def append_jsonl(path: str, entry: dict) -> None:
    if not path:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "a", encoding="utf-8") as hf:
        hf.write(json.dumps(entry) + "\n")


def write_json(path: str, entry: dict) -> None:
    if not path:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as jf:
        json.dump(entry, jf, indent=2)


def main() -> int:
    args = parse_args()

    now = parse_ts(args.now) if args.now else dt.datetime.now(dt.timezone.utc)
    window_start = now - dt.timedelta(hours=args.hours)

    files = sorted(glob.glob(args.sessions_glob))
    if not files:
        print("# OpenClaw Spend Report\n\nNo session logs found.")
        return 0

    assistant_turns = []
    tool_counts = Counter()
    session_totals = defaultdict(lambda: {"tokens": 0, "cost": 0.0, "assistant": 0, "tool_turns": 0})
    session_id_by_file = {}

    for fp in files:
        session_id = os.path.basename(fp).replace(".jsonl", "")
        session_id_by_file[fp] = session_id
        with open(fp, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    obj = json.loads(line)
                except Exception:
                    continue
                if obj.get("type") != "message":
                    continue
                msg = obj.get("message") or {}
                if msg.get("role") != "assistant":
                    continue

                ts = parse_ts(obj.get("timestamp"))
                if not ts or ts < window_start:
                    continue

                usage = msg.get("usage") or {}
                tokens = int(usage.get("totalTokens") or 0)
                cost = float(((usage.get("cost") or {}).get("total")) or 0.0)

                tools = []
                for content in msg.get("content") or []:
                    if (content or {}).get("type") == "toolCall":
                        name = (content or {}).get("name")
                        if name:
                            tools.append(name)
                tool_counts.update(tools)

                sid = session_id_by_file[fp]
                record = session_totals[sid]
                record["tokens"] += tokens
                record["cost"] += cost
                record["assistant"] += 1
                if tools:
                    record["tool_turns"] += 1

                assistant_turns.append((ts, tokens, cost, tuple(tools), sid))

    if not assistant_turns:
        print(f"# OpenClaw Spend Report\n\nNo assistant turns in the last {args.hours:g}h.")
        return 0

    assistant_turns.sort(key=lambda x: x[0])

    total_tokens = sum(turn[1] for turn in assistant_turns)
    total_cost = sum(turn[2] for turn in assistant_turns)
    count = len(assistant_turns)
    avg_tokens = total_tokens / max(count, 1)
    max_tokens = max(turn[1] for turn in assistant_turns)

    top_turns = sorted(assistant_turns, key=lambda x: x[1], reverse=True)[:5]

    per_session = sorted(
        ((sid, st["assistant"], st["tool_turns"], st["tokens"], st["cost"]) for sid, st in session_totals.items()),
        key=lambda x: x[3],
        reverse=True,
    )[:10]

    print("# OpenClaw Spend Report")
    print("")
    print(
        f"Window: last {args.hours:g}h (UTC) — {window_start.isoformat(timespec='seconds')} → {now.isoformat(timespec='seconds')}"
    )
    print("")
    print("## Totals (assistant turns only)")
    print(f"- Assistant turns: **{count}**")
    print(f"- Total tokens: **{total_tokens:,}**")
    print(f"- Total cost: **{money(total_cost)}**")
    print(f"- Avg tokens/turn: **{avg_tokens:,.0f}**")
    print(f"- Max tokens/turn: **{max_tokens:,}**")
    print("")

    print("## Top tool calls")
    for name, n in tool_counts.most_common(8):
        print(f"- {name}: {n}")
    if not tool_counts:
        print("- (no tool calls)")
    print("")

    print("## Largest turns (by total tokens)")
    for ts, tokens, cost, tools, sid in top_turns:
        tool_str = ",".join(tools) if tools else "none"
        print(
            f"- {ts.isoformat(timespec='seconds')} — {tokens:,} tokens — {money(cost)} — tools={tool_str} — session={sid}"
        )
    print("")

    print("## Per-session totals (top 10)")
    for sid, a_cnt, tool_cnt, tok, cost in per_session:
        print(f"- {sid}: turns={a_cnt}, tool-turns={tool_cnt}, tokens={tok:,}, cost={money(cost)}")

    snapshot = {
        "generatedAt": now.isoformat(timespec="seconds"),
        "window": {
            "hours": args.hours,
            "start": window_start.isoformat(timespec="seconds"),
            "end": now.isoformat(timespec="seconds"),
        },
        "totals": {
            "assistantTurns": count,
            "totalTokens": total_tokens,
            "totalCost": total_cost,
            "avgTokensPerTurn": avg_tokens,
            "maxTokensPerTurn": max_tokens,
        },
        "toolCalls": dict(tool_counts.most_common()),
        "largestTurns": [
            {
                "ts": ts.isoformat(timespec="seconds"),
                "tokens": tokens,
                "cost": cost,
                "tools": list(tools),
                "session": sid,
            }
            for ts, tokens, cost, tools, sid in top_turns
        ],
        "perSession": [
            {
                "session": sid,
                "assistantTurns": a_cnt,
                "toolTurns": tool_cnt,
                "tokens": tok,
                "cost": cost,
            }
            for sid, a_cnt, tool_cnt, tok, cost in per_session
        ],
    }

    if args.json_out:
        write_json(args.json_out, snapshot)

    if args.history_out:
        append_jsonl(args.history_out, snapshot)

    if args.journal_out or args.journal_history:
        log_title, log_lines = read_last_log_block(args.coo_log)
        todo_items = parse_todo_items(args.todo)
        journal_entry = build_journal_entry(
            now, args.hours, total_tokens, total_cost, log_title, log_lines, todo_items
        )
        if args.journal_out:
            write_json(args.journal_out, journal_entry)
        if args.journal_history:
            append_jsonl(args.journal_history, journal_entry)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
